- name: Deploy Hello World Module
  hosts: all
  remote_user: "{{ username }}"
  vars:
    remote_image: "docker://ksmith21/{{ software_name }}:{{ version }}"

  tasks:
    - name: Ensure required directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ module_dir }}"
        - "{{ software_dir }}"

    - name: Load Singularity module and Pull image
      shell: |
        module load singularity/{{ singularity_version }}
        singularity pull -F {{ software_path }} {{ remote_image }}
      args:
        executable: /bin/bash

    - name: Create module file
      template:
        src: modulefile.lua.jinja2
        dest: "{{ module_file_path }}"
        mode: "0644"
